### ISSUE TITLE
Error message : holders of that lock are waiting for ForsetiClient on "Requesting : Objects with path to DA"

### ISSUE THREAD

**Issue by RomainSec** [Mazars-Tech/AD_Miner#132]
Error messages appearing while launching the tool :

[!]{code: Neo.TransientError.Transaction.DeadlockDetected} {message: ForsetiClient[transactionId=11316, clientId=49] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=11318, clientId=65]} on NODE(10408), because holders of that lock are waiting for ForsetiClient[transactionId=11316, clientId=49].
 Wait list:ExclusiveLock[
Client[11318] waits for [ForsetiClient[transactionId=11316, clientId=49],ForsetiClient[transactionId=11320, clientId=67]]]}
[!]multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\ad_miner\sources\modules\neo4j_class.py", line 284, in executeParallelRequest
    for record in tx.run(q):
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\work\result.py", line 251, in __iter__
    self._connection.fetch_message()
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\io\_common.py", line 180, in inner
    func(*args, **kwargs)
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\io\_bolt.py", line 658, in fetch_message
    res = self._process_message(tag, fields)
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\io\_bolt4.py", line 326, in _process_message
    response.on_failure(summary_metadata or {})
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\neo4j\_sync\io\_common.py", line 247, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.TransientError: {code: Neo.TransientError.Transaction.DeadlockDetected} {message: ForsetiClient[transactionId=11316, clientId=49] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=11318, clientId=65]} on NODE(10408), because holders of that lock are waiting for ForsetiClient[transactionId=11316, clientId=49].
 Wait list:ExclusiveLock[
Client[11318] waits for [ForsetiClient[transactionId=11316, clientId=49],ForsetiClient[transactionId=11320, clientId=67]]]}
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\ad_miner\__main__.py", line 77, in populate_data_and_cache
    neo4j.process_request(neo4j, request_key)
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\ad_miner\sources\modules\neo4j_class.py", line 375, in process_request
    result = self.parallelWriteRequest(self, items)
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\ad_miner\sources\modules\neo4j_class.py", line 635, in parallelRequestLegacy
    for _ in tqdm.tqdm(
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\ad_miner\sources\modules\istarmap.py", line 19, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 873, in next
    raise value
neo4j.exceptions.TransientError: {code: Neo.TransientError.Transaction.DeadlockDetected} {message: ForsetiClient[transactionId=11316, clientId=49] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=11318, clientId=65]} on NODE(10408), because holders of that lock are waiting for ForsetiClient[transactionId=11316, clientId=49].
 Wait list:ExclusiveLock[
Client[11318] waits for [ForsetiClient[transactionId=11316, clientId=49],ForsetiClient[transactionId=11320, clientId=67]]]}

Then it continues its things and when requests are finished :

[+]Requests finished !
[+]Computing domains objects
Traceback (most recent call last):
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\Scripts\AD-miner.exe\__main__.py", line 7, in <module>
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\ad_miner\__main__.py", line 182, in main
    domains = Domains(arguments, neo4j)
  File "C:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\ad_miner\sources\modules\domains.py", line 29, in __init__
    self.objects_to_domain_admin = neo4j.all_requests["objects_to_domain_admin"][
KeyError: 'result'

Thanks for your help

**Comment by RomainSec** [comment]
System information

    AD_Miner 1.2.0, installed using Python Python 3.10.11 on Windows
    Classic Bloodhound
    Data collected with Sharphound

**Comment by snowpeacock** [comment]
Hello,
my guess is that you have bloodhound open and you are doing analysis / other queries in the same time.

The first error looks like the neo4j database can't perform an AD Miner request because it is being used / edited in the same time. Then it fails because one important request couldn't be completed.

Try to close bloodhound and re-launch AD Miner without cache
