### ISSUE TITLE
Error in genDAPage `argument of type 'NoneType' is not iterable`

### ISSUE THREAD

**Issue by 0xArt3mis** [Mazars-Tech/AD_Miner#153]
**Describe the bug**
I get the following error when generating the report pages: 
`AD-miner -c -cf Report -u $user -p $pw`

**Terminal Output**
```
[+]Requests finished !
[+]Computing domains objects
[+]Split objects into types...
[+][Done]
[+]... from OUs
[+]... from GPOs
[+]... from groups
[+]... from OUs
[+]... from GPOs
[+]Generate paths to Kerberos Unconstrained Delegations
Traceback (most recent call last):
  File "/root/AD_Miner/.venv/bin/AD-miner", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/AD_Miner/ad_miner/__main__.py", line 183, in main
    domains = Domains(arguments, neo4j)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/AD_Miner/ad_miner/sources/modules/domains.py", line 266, in __init__
    self.genDAPage()
  File "/root/AD_Miner/ad_miner/sources/modules/domains.py", line 448, in genDAPage
    if "Domain Admin" in da["admin type"]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**System information**
 - Kali
 - Python 3.11.9

**Comment by jmbesnard** [comment]
Thanks for reporting this. I have some troubleshooting questions that are going to be easier to ask over a chat. Feel free to join our discord server.

**Comment by snowpeacock** [comment]
Hello @0xArt3mis , thanks for reporting this. 
Did you encounter any other error during the queries ?

**Comment by jmbesnard** [comment]
Closing this issue as we did not get any feedback
