### ISSUE TITLE
Error on Windows 11

### ISSUE THREAD

**Issue by M4TXRX** [Mazars-Tech/AD_Miner#176]
Hi,

I have an error when i try to execute ad-miner on Windows 11 :

AD-miner -c -cf project -b bolt://localhost:7687 -u neo4j -p pass
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\pipx\bin\AD-miner.exe\__main__.py", line 7, in <module>
  File "C:\pipx\venvs\ad-miner\Lib\site-packages\ad_miner\__main__.py", line 149, in main
    extract_date, total_objects, number_relations, boolean_azure = pre_request(arguments)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pipx\venvs\ad-miner\Lib\site-packages\ad_miner\sources\modules\neo4j_class.py", line 92, in pre_request
    for record in tx.run(
                  ^^^^^^^
  File "C:\pipx\venvs\ad-miner\Lib\site-packages\neo4j\_sync\work\transaction.py", line 156, in run
    result._tx_ready_run(query, parameters)
  File "C:\pipx\venvs\ad-miner\Lib\site-packages\neo4j\_sync\work\result.py", line 120, in _tx_ready_run
    self._run(query, parameters, None, None, None, None)
  File "C:\pipx\venvs\ad-miner\Lib\site-packages\neo4j\_sync\work\result.py", line 166, in _run
    self._attach()
  File "C:\pipx\venvs\ad-miner\Lib\site-packages\neo4j\_sync\work\result.py", line 274, in _attach
    self._connection.fetch_message()
  File "C:\pipx\venvs\ad-miner\Lib\site-packages\neo4j\_sync\io\_common.py", line 180, in inner
    func(*args, **kwargs)
  File "C:\pipx\venvs\ad-miner\Lib\site-packages\neo4j\_sync\io\_bolt.py", line 658, in fetch_message
    res = self._process_message(tag, fields)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pipx\venvs\ad-miner\Lib\site-packages\neo4j\_sync\io\_bolt5.py", line 317, in _process_message
    response.on_failure(summary_metadata or {})
  File "C:\pipx\venvs\ad-miner\Lib\site-packages\neo4j\_sync\io\_common.py", line 247, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: The property existence syntax `... exists(variable.property)` is no longer supported. Please use `variable.property IS NOT NULL` instead. (line 1, column 17 (offset: 16))
"MATCH (n) WHERE EXISTS(n.tenantid) return n LIMIT 1"
```

 python 3.11.5 and neo4j==4.3.0 and  Neo4j Desktop 1.6.0

**Comment by M4TXRX** [comment]
Install DBMS 4.X on neo4j solved the issue.

**Comment by M4TXRX** [comment]
Install DBMS 4.X on neo4j solved the issue.
